source 'https://rubygems.org'

parent_dir = File.expand_path('../..', __FILE__)
if File.exists? "#{parent_dir}/pacto.gemspec"
  # development
  path parent_dir do
    gem 'pacto'
    gem 'pacto-server'
  end
else
  # released gems
  gem 'pacto'
  gem 'pacto-server'
end

gem 'grape'
gem 'grape-swagger'
gem 'puma'
gem 'rspec' #, '~> 3.0.0.beta2'
gem 'rake'
gem 'pry'
gem 'rack'
