source 'https://rubygems.org'

if File.exists? '../pacto.gemspec'
  gem 'pacto', :path => '..' # development
else
  gem 'pacto' # released
end

gem 'octokit', '~> 2.7'
gem 'rspec', '~> 3.0.0.beta2'
gem 'rake'
gem 'pry'
